spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql7.sqlpub.com:3312/lylyly_database?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: lylyly
    password: TGDZqI02zkUBqSoV
mybatis:
  configuration:
    map-underscore-to-camel-case: true